package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - CreateProductQuantityEncodedKeyFromEncodedProductId - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class CreateProductQuantityEncodedKeyFromEncodedProductId
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public CreateProductQuantityEncodedKeyFromEncodedProductId(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ProductQuantityIf createProductQuantityEncodedKeyFromEncodedProductId( String encodedProductId) throws KKException
     {
         return kkEng.createProductQuantityEncodedKeyFromEncodedProductId(encodedProductId);
     }
}
