package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - ExternalLogin - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class ExternalLogin
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public ExternalLogin(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ExternalLoginResultIf externalLogin(ExternalLoginInputIf loginInfo) throws KKException
     {
         return kkEng.externalLogin(loginInfo);
     }
}
