package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetConfigurationNoCache - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetConfigurationNoCache
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetConfigurationNoCache(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public KKConfigurationIf getConfigurationNoCache(String key) throws KKException
     {
         return kkEng.getConfigurationNoCache(key);
     }
}
