package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - RemoveStockReservationsForBasketItems - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class RemoveStockReservationsForBasketItems
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public RemoveStockReservationsForBasketItems(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public int removeStockReservationsForBasketItems(String sessionId, BasketIf[] basketItems, StockReservationOptionsIf options) throws KKException
     {
         return kkEng.removeStockReservationsForBasketItems(sessionId, basketItems, options);
     }
}
