package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - RemoveStockReservationsForIds - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class RemoveStockReservationsForIds
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public RemoveStockReservationsForIds(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public int removeStockReservationsForIds(String sessionId, int[] idArray, StockReservationOptionsIf options) throws KKException
     {
         return kkEng.removeStockReservationsForIds(sessionId, idArray, options);
     }
}
